### ISSUE TITLE
Reprocess critical facilities

### ISSUE THREAD

**Issue by dichapabe** [UPRI-NOAH/mapbox-processor#5]
**Tasks:**

- [x] Download shapefile using gdrive sync
- [x] Process critical facilities
- [x] Give the list of the uploaded tilesets to Jad
