### ISSUE TITLE
Comparison of Different Precisions

### ISSUE THREAD

**Issue by dichapabe** [UPRI-NOAH/mapbox-processor#7]
**Tasks:**

Using 100yr MM Flood Hazard
- [x] Process and upload using 10m Precision
- [x] Process and upload using 1m Precision
- [x] Compare Tiled Area
- [x] Compare Tile Hosting and Processing Price
